name = "ingest-worker"
main = "src/index.ts"
compatibility_date = "2023-09-05"

[vars]
telegrafUrl = "https://telegraf.sdnts.dev/api/v2/write?precision=ms"
allowedOrigins = [
  "https://dietcode.io",
  "https://blob.city",
  "https://api.blob.city",
]
