name = "ingest-worker"
main = "src/index.ts"
compatibility_date = "2023-02-19"

[vars]
TELEGRAF_URL = "https://telegraf.sdnts.dev/api/v2/write?precision=ms"
ALLOWED_ORIGINS = [
  "https://dietcode.io",
  "https://blob.city",
  "https://api.blob.city"
]
